server:
  port: 9001
spring:
  application:
    name: wangyanbao-base
#===================================
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.19.132:3306/tensquare_base?characterEncoding=utf-8
    username: root
    password: root
#================================
  redis:
    host: 192.168.19.132

eureka:
  client:
    service-url:
       defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true



mybatis:
  type-aliases-package: com.wangyanbao.base.pojo
  mapper-locations: classpath:mapper/*.xml
#==============分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql
eureka:
  client:
    service-url:
       defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true




