server:
  port: 9004
spring:
  application:
    name: wangyanbao-article
#===================================
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.19.132:3306/tensquare_article?characterEncoding=utf-8
    username: root
    password: root
#================================
  redis:
    host: 192.168.19.132





mybatis:
  type-aliases-package: com.wangyanbao.article.pojo
  mapper-locations: classpath:mapper/*.xml
#==============分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql





