server:
  port: 9002
spring:
  application:
    name: wangyanbao-recruit
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.19.132:3306/tensquare_recruit?characterEncoding=utf-8
    username: root
    password: root
mybatis:
  type-aliases-package: com.wangyanbao.recruit.pojo
  mapper-locations: classpath:mapper/*.xml
#==============分页
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql